### ISSUE TITLE
Participant leave the event

### ISSUE THREAD

**Issue by BenCheng2** [CSC207-2022F-UofT/course-project-group-71#12]
The participant decide to not join the event that he/she registered, so he/she click the button to leave the event.

**Comment by BenCheng2** [comment]
A participant have already registered in an event
The participant decide to leave the event
The system verify if the current user is a participant
The system verify if this participant registered in the event
The participant re-verify the leaving request
The participant got removed from the event’s participants list
The event got removed from the upcoming event list of the participant
Show success view
If failed in one of the steps, show failure view

**Comment by Anita-hua** [comment]
Since leaving the event will always be success, I don't think we need to separate into success and failure cases in the interactor and separate into different views. I think you can only keep the prepare success view and delete the failure one.

**Comment by AllysonCui** [comment]
par leave event should not be sending notifications to organization

**Comment by AllysonCui** [comment]
this use case should be in the par upcoming event page

**Comment by BenCheng2** [comment]
It does not have a failure view because there's no need for it, the participant won't see the button of leave, so it's fine with just one success view model.

**Comment by ChrisSong1** [comment]
Since only the participant interface displays the leave button, we do not need to use a boolean to determine whether the user is a Participant or organizer

**Comment by ChrisSong1** [comment]
For ResponseModel, we just need two variables"event_title" and "message" and don't need the user_name.
