### ISSUE TITLE
Organization send notification to participants

### ISSUE THREAD

**Issue by BenCheng2** [CSC207-2022F-UofT/course-project-group-71#13]
The organization think it's important to mention the participants about the event so the organization send them notification.

**Comment by BenCheng2** [comment]
Organization clicks “Upcoming Events” button, directs to the upcoming events page
Organization clicks “Notify” button of one event, this sends the notification to all participants of the event

**Comment by AllysonCui** [comment]
will need to comply with both delete event and notify event use case

**Comment by AllysonCui** [comment]
connects with the show notification button on the par home page

**Comment by Anita-hua** [comment]
If there are no notifications we should still return something like "you don't have notification!" And do we have to set a fix size for the pop-up windows of the notification?

**Comment by Baaadmtfka** [comment]
prepareView is returning a ShowMessageView which throws an exception. Need to separate prepareView into one success and one failure

**Comment by BenCheng2** [comment]
This method is on the OrgUpcomingEventPage, its action is heard by OrgUpcomingEventPageActionListener, now it have three buttons 'Back', which close the current page and send us to the home page, 'Notify' buttons for each events sent each participants notifications. And 'Delete' delete the event from the upcoming event.
