### ISSUE TITLE
Participant follows an organization

### ISSUE THREAD

**Issue by BenCheng2** [CSC207-2022F-UofT/course-project-group-71#14]
The participant wants to be notified of future event created by the organization so the participant follows the organization

**Comment by BenCheng2** [comment]
Participant searches for organizer in the search bar
A list of organizers which contain the user search (string) is returned and formatted to display for the user
User chooses organizer and clicks “follow button” on the UI
The followed organizer adds participant to their followed list attribute
The participant adds organizer to their following list attribute

**Comment by AllysonCui** [comment]
needs to show the difference between followed org and unfollowed org

**Comment by AllysonCui** [comment]
org title needs to a button which will directs to the org detail page

**Comment by AllysonCui** [comment]
the org page could be a joptionpane, no back button

**Comment by AllysonCui** [comment]
org detail page can contain 3 latest upcoming event

**Comment by AndytheCreator223** [comment]
there could be some issues with displaying 3 latest upcoming event on org details page, because edge cases when organizers has only 1 or 2 event

**Comment by BenCheng2** [comment]
The following relationship in the database is built by one table, not two. In searched result page of the searching method, it gave the following button and an unfollowing button.
