### ISSUE TITLE
Database_testing

### ISSUE THREAD

**Issue by BenCheng2** [CSC207-2022F-UofT/course-project-group-71#17]

**Comment by AllysonCui** [comment]
Remove main in the fileuser

**Comment by AllysonCui** [comment]
first letter of method should be in lower case

**Comment by AllysonCui** [comment]
Event's date can be 5 integers instead of LocalDateTime, which are year, month, date, month, minute

**Comment by BenCheng2** [comment]
Almost finished
Now lacking: testing (which involves JDBC testing, not easy), comment on each method, and organization of the tool class.

**Comment by AllysonCui** [comment]
The participant's attribute notification should be ArrayList<String> as we may have more than 1 notification at one time.

**Comment by AllysonCui** [comment]
Therefore I need 3 ParFileUser methods
ArrayList<String> getNotifications(String username)
void clearNotifications(String username)
void addNotification(String notification)

**Comment by AllysonCui** [comment]
getLocation also seems to be wrong, please check if it is pointing at the correct database column

**Comment by BenCheng2** [comment]
The exception is not properly dealt with, the exception is found and caught but it's not processed(threw), we need to change every code related with try and exception.

**Comment by BenCheng2** [comment]
Test finished from a database called testing_db, all three database are available, documented, tested

**Comment by Anita-hua** [comment]
All three participants, organizers, and event databases seems finished and the the database will work with other use cases. So it can be pulled requested to main.

**Comment by Baaadmtfka** [comment]
Though there could be some little tweaks to achieve perfection, all databases seem completed and functions just fine.
