### ISSUE TITLE
Search for events and organizers

### ISSUE THREAD

**Issue by BenCheng2** [CSC207-2022F-UofT/course-project-group-71#6]
Gavin is searching for an event. He types in several keywords and is able to find events with words in the titles that match the keywords inputted. He sees these results sorted from most to least relevant (based on the amount of matching words).

**Comment by BenCheng2** [comment]
A participant want to search the events interested
The participant use the searching bar and enter the keyword of the interest
The system navigate through the event list and looking for the matched event
The system return events that might be related to the keyword
Show success view
If no events found, show failure view

**Comment by AllysonCui** [comment]
the views can be divided into two screens depending on whether the user is searching on organization or event

**Comment by AllysonCui** [comment]
the result page can be a joptionpane so no back button

**Comment by AllysonCui** [comment]
the participant must select a type to continue to the search steps

**Comment by AllysonCui** [comment]
this search use case can be put into the par home page

**Comment by AllysonCui** [comment]
Search method would be check if the title or username includes the string typed in the search box

**Comment by Baaadmtfka** [comment]
Search functions just fine, all tests have passed.

**Comment by AndytheCreator223** [comment]
If the user did not type anything into the search bar and chose either organizer or event before clicking search, it should return all the organizers and upcoming events in the database
